name: Build & Release

# Adapted from https://github.com/larsboes/obsidian-bases-charts-plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: obsidian-gcal-sync

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine prerelease status
        id: status
        run: |
          if [[ "${{ github.ref }}" == *"canary"* ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build
        run: |
          bun install
          bun run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp dist/main.js manifest.json manifest-beta.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip ${{ env.PLUGIN_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.status.outputs.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
            dist/main.js
            manifest.json
            manifest-beta.json
